version: '3.6'
services:
  redis:
    image: "redis:6.2.1-alpine"
    ports:
      - "6379:6379"
  minio:
    image: minio/minio
    volumes:
      - data:/data
    entrypoint: >
      /bin/sh -c "
      mkdir -p /data/yourbucket;
      /usr/bin/minio server /data;
      "
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
      - MINIO_DIR=/data

  clockwork-event-sourcing:
      build: .
      image: "clockwork-event-sourcing"
      container_name: cw
      ports:
      - "5000:5000"
      depends_on:
        - redis
        - minio
volumes:
  data: