version: '3.6'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  minio:
    image: minio/minio
    entrypoint: >
      /bin/sh -c "
      mkdir -p /data/yourbucket;
      /usr/bin/minio server /data;
      "
    ports:
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
      - MINIO_DIR=/data
    volumes:
      - ./test/datalake:/data
  clockwork:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint:
      - "/bin/bash"
      - "-c"
      - "./wait-for-it.sh -t 60 redis:6379 && ./wait-for-it.sh -t 60 minio:9000 -- yarn test"
    depends_on:
      - redis
      - minio
