apiVersion: v1
kind: Service
metadata:
  name: {{ include "deployment.name" . }}
  labels: {{ include "labels.common" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.service.internalPort }}
    protocol: TCP
    targetPort: app
    name: app
  selector: {{ include "labels.deployment" . | nindent 4 }}
  type: {{ .Values.service.type }}
